// Generated by CoffeeScript 1.8.0
(function() {
  var OpenvpnClientService, OpenvpnMgmtClient, OpenvpnServerService, OpenvpnService, StormService, fs, merge,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  StormService = require('stormservice');

  merge = require('fmerge');

  fs = require('fs');

  OpenvpnService = (function(_super) {
    __extends(OpenvpnService, _super);

    OpenvpnService.prototype.invocation = {
      name: 'openvpn',
      path: '/usr/sbin',
      monitor: true,
      args: [],
      options: {
        detached: true,
        stdio: ["ignore", -1, -1]
      }
    };

    function OpenvpnService(id, data, opts) {
      if (data.instance != null) {
        this.instance = data.instance;
        delete data.instance;
      }
      if (opts == null) {
        opts = {};
      }
      if (opts.configPath == null) {
        opts.configPath = "/var/stormflash/plugins/openvpn";
      }
      if (opts.logPath == null) {
        opts.logPath = "/var/log/openvpn";
      }
      OpenvpnService.__super__.constructor.call(this, id, data, opts);
      this.configs = {
        service: {
          filename: "" + this.configPath + "/" + this.id + ".conf"
        }
      };
      this.invocation = merge(this.invocation, {
        args: ["--config", "" + this.configs.service.filename],
        options: {
          stdio: ["ignore", this.out, this.err]
        }
      });
      this.configs.service.generator = (function(_this) {
        return function(callback) {
          var i, key, val, vpnconfig, _i, _len, _ref;
          vpnconfig = '';
          _ref = _this.data;
          for (key in _ref) {
            val = _ref[key];
            switch (typeof val) {
              case "object":
                if (val instanceof Array) {
                  for (_i = 0, _len = val.length; _i < _len; _i++) {
                    i = val[_i];
                    if (key === "route") {
                      vpnconfig += "" + key + " " + i + "\n";
                    }
                    if (key === "push") {
                      vpnconfig += "" + key + " \"" + i + "\"\n";
                    }
                  }
                }
                break;
              case "number":
              case "string":
                vpnconfig += key + ' ' + val + "\n";
                break;
              case "boolean":
                vpnconfig += key + "\n";
            }
          }
          vpnconfig += ("management " + _this.configPath + "/" + _this.id + "_mgmt.sock  unix") + "\n";
          return callback(vpnconfig);
        };
      })(this);
    }

    OpenvpnService.prototype.destructor = function() {
      this.eliminate();
      return this.emit('destroy');
    };

    return OpenvpnService;

  })(StormService);

  OpenvpnServerService = (function(_super) {
    __extends(OpenvpnServerService, _super);

    function OpenvpnServerService(id, data, opts) {
      var ccdpath, err;
      this.schema = {
        name: "openvpn",
        type: "object",
        additionalProperties: true,
        properties: {
          id: {
            "type": "string",
            "required": false
          },
          port: {
            "type": "number",
            "required": true
          },
          dev: {
            "type": "string",
            "required": true
          },
          proto: {
            "type": "string",
            "required": true
          },
          ca: {
            "type": "string",
            "required": true
          },
          dh: {
            "type": "string",
            "required": true
          },
          cert: {
            "type": "string",
            "required": true
          },
          key: {
            "type": "string",
            "required": true
          },
          server: {
            "type": "string",
            "required": true
          },
          'ifconfig-pool-persist': {
            "type": "string",
            "required": false
          },
          'script-security': {
            "type": "string",
            "required": false
          },
          multihome: {
            "type": "boolean",
            "required": false
          },
          management: {
            "type": "string",
            "required": false
          },
          cipher: {
            "type": "string",
            "required": false
          },
          'tls-cipher': {
            "type": "string",
            "required": false
          },
          auth: {
            "type": "string",
            "required": false
          },
          topology: {
            "type": "string",
            "required": false
          },
          'route-gateway': {
            "type": "string",
            "required": false
          },
          'client-config-dir': {
            "type": "string",
            "required": false
          },
          'ccd-exclusive': {
            "type": "boolean",
            "required": false
          },
          'client-to-client': {
            "type": "boolean",
            "required": false
          },
          route: {
            items: {
              type: "string"
            }
          },
          push: {
            items: {
              type: "string"
            }
          },
          'tls-timeout': {
            "type": "number",
            "required": false
          },
          'max-clients': {
            "type": "number",
            "required": false
          },
          'persist-key': {
            "type": "boolean",
            "required": false
          },
          'persist-tun': {
            "type": "boolean",
            "required": false
          },
          status: {
            "type": "string",
            "required": false
          },
          keepalive: {
            "type": "string",
            "required": false
          },
          'comp-lzo': {
            "type": "string",
            "required": false
          },
          sndbuf: {
            "type": "number",
            "required": false
          },
          rcvbuf: {
            "type": "number",
            "required": false
          },
          txqueuelen: {
            "type": "number",
            "required": false
          },
          'replay-window': {
            "type": "string",
            "required": false
          },
          'duplicate-cn': {
            "type": "boolean",
            "required": false
          },
          'log-append': {
            "type": "string",
            "required": false
          },
          verb: {
            "type": "number",
            "required": false
          },
          mlock: {
            "type": "boolean",
            "required": false
          },
          'tun-mtu': {
            "type": "number",
            "required": false
          },
          mssfix: {
            "type": "string",
            "required": false
          }
        }
      };
      ccdpath = data["client-config-dir"];
      if (ccdpath != null) {
        try {
          fs.mkdir("" + ccdpath, function() {});
        } catch (_error) {
          err = _error;
        }
      }
      OpenvpnServerService.__super__.constructor.call(this, id, data, opts);
    }

    return OpenvpnServerService;

  })(OpenvpnService);

  OpenvpnClientService = (function(_super) {
    __extends(OpenvpnClientService, _super);

    function OpenvpnClientService(id, data, opts) {
      this.schema = {
        name: "openvpn",
        type: "object",
        additionalProperties: true,
        properties: {
          id: {
            "type": "string",
            "required": false
          },
          pull: {
            "type": "boolean",
            "required": true
          },
          'tls-client': {
            "type": "boolean",
            "required": true
          },
          dev: {
            "type": "string",
            "required": true
          },
          proto: {
            "type": "string",
            "required": false
          },
          ca: {
            "type": "string",
            "required": true
          },
          dh: {
            "type": "string",
            "required": false
          },
          cert: {
            "type": "string",
            "required": true
          },
          key: {
            "type": "string",
            "required": true
          },
          remote: {
            "type": "string",
            "required": true
          },
          cipher: {
            "type": "string",
            "required": false
          },
          'tls-cipher': {
            "type": "string",
            "required": false
          },
          'remote-random': {
            "type": "boolean",
            "required": false
          },
          'resolv-retry': {
            "type": "string",
            "required": false
          },
          ping: {
            "type": "number",
            "required": false
          },
          'ping-restart': {
            "type": "number",
            "required": false
          },
          log: {
            "type": "string",
            "required": false
          },
          route: {
            items: {
              type: "string"
            }
          },
          push: {
            items: {
              type: "string"
            }
          },
          'persist-key': {
            "type": "boolean",
            "required": false
          },
          'persist-tun': {
            "type": "boolean",
            "required": false
          },
          status: {
            "type": "string",
            "required": false
          },
          'comp-lzo': {
            "type": "string",
            "required": false
          },
          verb: {
            "type": "number",
            "required": false
          },
          mlock: {
            "type": "boolean",
            "required": false
          }
        }
      };
      OpenvpnClientService.__super__.constructor.call(this, id, data, opts);
    }

    return OpenvpnClientService;

  })(OpenvpnService);

  OpenvpnMgmtClient = (function() {
    var net;

    net = require("net");

    function OpenvpnMgmtClient(context) {
      this.client = null;
    }

    OpenvpnMgmtClient.prototype.connect = function(options, callback) {
      this.client = net.connect(options, (function(_this) {
        return function(result) {
          _this.client.setEncoding('utf8');
          return callback(null, _this.client);
        };
      })(this));
      this.client.on('error', (function(_this) {
        return function(err) {
          console.log('vpn mgmt client connection error :', err.message);
          return callback(err, null);
        };
      })(this));
      return this.client.on('end', (function(_this) {
        return function() {
          return console.log('vpn mgmt client disconnected :');
        };
      })(this));
    };

    OpenvpnMgmtClient.prototype.execute = function(command, callback) {
      if (this.client != null) {
        console.log("command ", command);
        this.client.write(command);
        return this.client.on("data", (function(_this) {
          return function(data) {
            var message;
            console.log("in client data ", data);
            console.log("vpn mgmt parsing data ", data.toString());
            message = String(data);
            if ((message.indexOf('ERROR')) >= 0) {
              return callback('error in executing command', null);
            } else {
              return callback(null, true);
            }
          };
        })(this));
      } else {
        return callback("error", null);
      }
    };

    OpenvpnMgmtClient.prototype.disconnect = function() {
      var err;
      try {
        return this.client.end();
      } catch (_error) {
        err = _error;
        return console.log("unable to properly terminate vpn mgmt client: " + this.client, err);
      }
    };

    return OpenvpnMgmtClient;

  })();

  module.exports.OpenvpnService = OpenvpnService;

  module.exports.OpenvpnClient = OpenvpnClientService;

  module.exports.OpenvpnServer = OpenvpnServerService;

  module.exports.OpenvpnMgmtClient = OpenvpnMgmtClient;

}).call(this);
