// Generated by CoffeeScript 1.9.3
(function() {
  var OpenvpnClientService, OpenvpnRegistry, OpenvpnServerService, OpenvpnUserRegistry, async;

  OpenvpnRegistry = require('./openvpn-registry').OpenvpnRegistry;

  OpenvpnUserRegistry = require('./openvpn-registry').OpenvpnUserRegistry;

  OpenvpnClientService = require('./openvpn-service').OpenvpnClient;

  OpenvpnServerService = require('./openvpn-service').OpenvpnServer;

  async = require('async');

  this.include = function() {
    var agent, clientRegistry, fs, plugindir, serverRegistry, userRegistry;
    agent = this.settings.agent;
    if (agent == null) {
      throw new Error("this plugin requires to be running in the context of a valid StormAgent!");
    }
    plugindir = this.settings.plugindir;
    if (plugindir == null) {
      plugindir = "/var/stormflash/plugins/openvpn";
    }
    fs = require('fs');
    if (!fs.existsSync(plugindir)) {
      fs.mkdirSync(plugindir);
    }
    clientRegistry = new OpenvpnRegistry("client", plugindir + "/openvpn-clients.db");
    serverRegistry = new OpenvpnRegistry("server", plugindir + "/openvpn-servers.db");
    userRegistry = new OpenvpnUserRegistry(plugindir + "/openvpn-users.db");
    serverRegistry.on('ready', function() {
      var i, len, ref, results1, service;
      ref = this.list();
      results1 = [];
      for (i = 0, len = ref.length; i < len; i++) {
        service = ref[i];
        if (!(service instanceof OpenvpnServerService)) {
          continue;
        }
        agent.log("restore: trying to recover:", service);
        results1.push((function(service) {
          return service.generate(function(err) {
            if (err != null) {
              return agent.log("restore: openvpn " + service.id + " failed to generate configs!");
            }
            return agent.invoke(service, function(err, instance) {
              if (err != null) {
                return agent.log("restore: openvpn " + service.id + " invoke failed with:", err);
              } else {
                return agent.log("restore: openvpn " + service.id + " invoke succeeded wtih " + instance);
              }
            });
          });
        })(service));
      }
      return results1;
    });
    clientRegistry.on('ready', function() {
      var i, len, ref, results1, service;
      ref = this.list();
      results1 = [];
      for (i = 0, len = ref.length; i < len; i++) {
        service = ref[i];
        if (!(service instanceof OpenvpnClientService)) {
          continue;
        }
        agent.log("restore: trying to recover:", service);
        results1.push((function(service) {
          return service.generate(function(err) {
            if (err != null) {
              return agent.log("restore: openvpn " + service.id + " failed to generate configs!");
            }
            return agent.invoke(service, function(err, instance) {
              if (err != null) {
                return agent.log("restore: openvpn " + service.id + " invoke failed with:", err);
              } else {
                return agent.log("restore: openvpn " + service.id + " invoke succeeded wtih " + instance);
              }
            });
          });
        })(service));
      }
      return results1;
    });
    this.post({
      '/openvpn/server': function() {
        var err, service;
        try {
          service = new OpenvpnServerService(null, this.body, {});
        } catch (_error) {
          err = _error;
          return this.next(err);
        }
        return service.generate((function(_this) {
          return function(err, results) {
            if (err != null) {
              return _this.next(err);
            }
            agent.log("POST /openvpn/server generation results:", results);
            serverRegistry.add(service);
            return agent.invoke(service, function(err, instance) {
              if (err != null) {
                return _this.next(err);
              } else {
                return _this.send({
                  id: service.id,
                  running: true
                });
              }
            });
          };
        })(this));
      }
    });
    this.del({
      '/openvpn/server/:server': function() {
        var service;
        service = serverRegistry.get(this.params.server);
        if (service == null) {
          return this.send(404);
        }
        serverRegistry.remove(this.params.server);
        return this.send(204);
      }
    });
    this.put({
      '/openvpn/server/:server': function() {
        var service;
        service = serverRegistry.get(this.params.server);
        if (service == null) {
          return this.send(404);
        }
        return service.updateService(this.body, (function(_this) {
          return function(err, results) {
            if (err != null) {
              return _this.next(err);
            }
            agent.log("update :", results);
            return _this.send({
              updated: true
            });
          };
        })(this));
      }
    });
    this.post({
      '/openvpn/server/:server/users': function() {
        var fn, i, len, server, serverId, tasks, user, users;
        serverId = this.params.server;
        users = this.body;
        server = serverRegistry.get(serverId);
        if (!((serverId != null) && (users != null) && (server != null))) {
          return this.send(400);
        }
        if (!(users instanceof Array)) {
          users = [users];
        }
        tasks = {};
        fn = function(user) {
          return tasks[user.id] = function(callback) {
            var entry;
            user.ccdpath = server.data["client-config-dir"];
            entry = userRegistry.add(user.id, user);
            userRegistry.adduser(entry);
            return callback(null, entry);
          };
        };
        for (i = 0, len = users.length; i < len; i++) {
          user = users[i];
          fn(user);
        }
        return async.parallel(tasks, (function(_this) {
          return function(err, results) {
            if (err != null) {
              return _this.next(err);
            }
            return _this.send(results);
          };
        })(this));
      }
    });
    this.del({
      '/openvpn/server/:id/users/:user': function() {
        var entry, i, len, server, serverId, ulist, user, userId;
        serverId = this.params.id;
        userId = this.params.user;
        ulist = userRegistry.list();
        server = serverRegistry.get(serverId);
        if (ulist) {
          for (i = 0, len = ulist.length; i < len; i++) {
            entry = ulist[i];
            if (entry && entry.cname === userId) {
              user = entry;
            }
          }
        }
        if (!((serverId != null) && (user != null) && (server != null))) {
          return this.send(400);
        }
        return userRegistry.deleteuser(server.data, user, (function(_this) {
          return function(res) {
            if (!(res instanceof Error)) {
              userRegistry.remove(user.id);
              return _this.send({
                deleted: true
              });
            } else {
              return _this.next(new Error("Failed to delete openvpn user ! " + user.id));
            }
          };
        })(this));
      }
    });
    this.get({
      '/openvpn/server/:id': function() {
        var service;
        service = serverRegistry.get(this.params.id);
        if (service == null) {
          return this.send(404);
        } else {
          return this.send(service.data);
        }
      }
    });
    this.get({
      '/openvpn/server': function() {
        return this.send(serverRegistry.list());
      }
    });
    this.post({
      '/openvpn/client': function() {
        var err, service;
        try {
          service = new OpenvpnClientService(null, this.body, {});
        } catch (_error) {
          err = _error;
          return this.next(err);
        }
        return service.generate((function(_this) {
          return function(err, results) {
            if (err != null) {
              return _this.next(err);
            }
            agent.log("POST /openvpn/client generation results:", results);
            clientRegistry.add(service);
            return agent.invoke(service, function(err, instance) {
              if (err != null) {
                return _this.next(err);
              } else {
                return _this.send({
                  id: service.id,
                  running: true
                });
              }
            });
          };
        })(this));
      }
    });
    this.del({
      '/openvpn/client/:client': function() {
        var service;
        service = clientRegistry.get(this.params.client);
        if (service == null) {
          return this.send(404);
        }
        clientRegistry.remove(this.params.client);
        return this.send(204);
      }
    });
    this.get({
      '/openvpn/client/:id': function() {
        var service;
        service = clientRegistry.get(this.params.id);
        if (service == null) {
          return this.send(404);
        } else {
          return this.send(service.data);
        }
      }
    });
    return this.get({
      '/openvpn/client': function() {
        return this.send(clientRegistry.list());
      }
    });
  };

}).call(this);
