// Generated by CoffeeScript 1.4.0
(function() {
  var openvpn;

  openvpn = require('./openvpn');

  this.include = function() {
    var vpn;
    vpn = new openvpn(this.settings);
    this.post({
      '/openvpn/server': function() {
        var _this = this;
        return vpn.addserver(this.body, function(res) {
          if (!(res instanceof Error)) {
            return _this.send(res);
          } else {
            return _this.next(new Error("Invalid openvpn server posting! " + res));
          }
        });
      }
    });
    this.del({
      '/openvpn/server/:server': function() {
        var _this = this;
        return vpn.deleteserver(this.params.server, function(res) {
          if (!(res instanceof Error)) {
            return _this.send(204);
          } else {
            return _this.next(new Error("Failed to delete openvpn server! " + res));
          }
        });
      }
    });
    this.post({
      '/openvpn/server/:server/users': function() {
        var _this = this;
        return vpn.adduser(this.params.server, this.body, function(res) {
          if (!(res instanceof Error)) {
            return _this.send(res);
          } else {
            return _this.next(new Error("Failed to add openvpn user! " + res));
          }
        });
      }
    });
    this.del({
      '/openvpn/server/:id/users/:user': function() {
        var _this = this;
        return vpn.deleteuser(this.params.id, this.params.user, function(res) {
          if (!(res instanceof Error)) {
            return _this.send(204);
          } else {
            return _this.next(new Error("Failed to delete openvpn user ! " + res));
          }
        });
      }
    });
    this.get({
      '/openvpn/server/:id': function() {
        var _this = this;
        return vpn.servers.get(this.params.id, function(res) {
          if (!(res instanceof Error)) {
            return _this.send(res);
          } else {
            return _this.next(new Error("Failed to get openvpn server! " + res));
          }
        });
      }
    });
    return this.get({
      '/openvpn/server': function() {
        var _this = this;
        return vpn.servers.list(function(res) {
          if (!(res instanceof Error)) {
            return _this.send(res);
          } else {
            return _this.next(new Error("Failed to list openvpn servers! " + res));
          }
        });
      }
    });
  };

}).call(this);
